### ISSUE TITLE
Suggest ideas for implementing a Singleton class

### ISSUE THREAD

**Issue by meganindya** [sugarlabs/musicblocks-2#12]
We shall use TypeScript 4 instead of JavaScript. We would require some "powerful objects" (not as God-like which we have in the original Music Blocks). Those need to be singleton.

Please suggest implementation techniques that enforce a singleton-like behavior. The leaner the better.

If you use some online code playground like [TS Playground](https://www.typescriptlang.org/play), it'll be easier to view.

**Comment by Nirali0029** [comment]
@meganindya  [https://medium.com/better-programming/3-ways-to-implement-the-singleton-pattern-in-typescript-with-node-js-75129f391c9b](url) This article may help.

**Comment by meganindya** [comment]
[My proposal](https://www.typescriptlang.org/play?#code/PQKhCgAIUgBBLAdgFwKYCcBmBDAxqqGAFQAt4BnSCyZE1KlDHfGk7ZSXAe3XVXIAOXRABNKyLq3rkkAcwA2qCYkhcARgCtUuZAHJKA9FwEZk8fgDpCkUtXIkuAV3kjIa+of6oUDSOS4AtvRctBiQmPCKkADu8LSQ2JC6FiIWyOS6kKgAHmiIMsJW0MDgSGhYePQAkgDKcorKkADeUJBtmFxcAFx+yOhyANytbWrY6D2IjgHu6EMAvuDgwMCQALTrq5AiqBGIcfDCaxvHJ6cbi6AQ0HC48tjk5NYAgjqU9wkx6NgCJujhPFI-PUlIdbvdKNtdvtCtZrAB5NTkDAAN3ooSo2xQ8AiYT4mAw3hYXFRvHg2zcAE9AdEvj8wod0Tx4LIkNh5Jw7g8tjskNDEPoMd4zDj0EViHRPt9fjF3tgRNtXBIsogOugWOichQ8kTMEkkORkNhEPhMtEyLgSFQ3r12PBcJBZEpymKStx8hw6ogFCDED0Wm02pdIABhYQG9COHQAoK0LipYrDSCIVDRAAUHS4AH4euG5AAaNxjbNJqYzACUPVqwOUQwDkCDnu9jX1huNqAsCbrLaN+ErjYahwAPpBHKIecmRPNIABeDngyD9n1UAICRRBFCUKtegcqf0By6J66wA223CHmCwQzwZHsAh1o-bci4foCMzCc8LiR8cQSmTbpfdm2kCpsILCAWYt4iGWRR1iAJR1leN5oDaZj2gA+oBvYLtWQ4jmOuyoJOiwIf0SH0GhGY5n0ciQMOo6QkghG1gGiG3pAaGjOMJbTGEdH4YxRGJge94Xm64aRl+H7Bnwt5vKIkB8MgjjoPkHzJtEDAnkBXC6uiYJctiqjJlsXD8PyHCagaBaoPISIKUoymqRq2RajRwjtue8EBmJfQSTw6adMWuZegWnHFpMPHoGWzSHgGhmpouygWBh7o9qg0V7ve96KY52H-klKVafgzFZQsWVtIlhSFa2LCzrQFBDLFbT1eQyUZjO-xcCV94tclnEdZx3ULEJYAfsehqoWNj7PvAr4HIgH4AOJOmEtDsPZSkqT+0g4SomEeSJXltCeqEOkomk1agqYZU1G25ZViDJftQ3EQGSIcBmAVcDd5WsBQbWdB1GYvYmjofZ011Uf0Xoxb9OUqX9rUUYD06o3hDETpAmaQAARDjkA9L1yNdYmw11u9hboKmnE-eVRP9bOg2k69bRg5TkPcTMsPlfDKj02MM5o-R46EVjaxVCqvLIFShNkEjTN1gscyNcsRzrDQ-AcGc2s6+siw+ZAV4oAACkYAiULOqZ-k2wgIhofa7bR6Mi1BPTIlwZIzgAfNzbTxdbO527TWViVwigWPIXCyFbu12xYGYFgHPpxzTQ1ZLZ9CZfeofh5H0c44gkj7TjZYvcNBvkNuEvkA7+W4cLBGuLOD0WM94BG8gpvGOQVtV-kpf62GHBoAadu1zbKizupeUT6mOMAOqoALiQBPcADWOMFgALAArAADHvA8d135upiPyBB41BtGiEdBcVuE8ddPD1zwAIsIugcNERrbOgJdDMfM2Pcb6hCio1EBd944o1xjUQ0VJ1oOCCDjK+Q8NYGmruPHcTsG4CQ6i3NugDu5n01tXAe4Bz4pwFrOHeNCd6NUIafc+pChhAA).

**Comment by ksraj123** [comment]
Maybe we could look into using factories of singletons. This approach would separate all the singleton instantiation code from our class declaration and would only require us to make one change i.e. turn the constructor of the concerned class `protected`. Also if we had to do some additional cumbersome configuration after instantiation of the class then we can also do that in the factory instead of crowding our class declaration with it. Since the factories would contain all the instantiation related code in one place (separation of concerns) the code will also be easy to understand and maintain.
  ```
  class PhraseMaker{
      val: number = 100 * Math.random();
  
      protected constructor(){
          console.log("Class A instantiated!");
      }
  }

// factory
class Widgets{
      private static _phraseMaker: PhraseMaker;
  
      private static PhraseMakerSingleton = class extends PhraseMaker {
          static create(){
              Widgets._phraseMaker = new PhraseMaker();
              /* Any lengthy additoanl configuration to be done after initialization can be done here */
          }
      }
      
      static get PhraseMaker(){
          if(Widgets._phraseMaker == null)
              Widgets.PhraseMakerSingleton.create();
          return Widgets._phraseMaker;
      }
  }
  
  console.log(Widgets.PhraseMaker.val);
  
  const { PhraseMaker: instance } = Widgets; // already had a variable named PhraseMaker, don't need to rename after destructuring
  
  console.log(instance.val);

```

Also, in client code we would have to import only one module (the concerned factory). This approach should make both the class declaration and client code leaner while providing more options for easy customisation in future through the factory.

Link to playground - [here](https://www.typescriptlang.org/play?#code/MYGwhgzhAEAKAWAnSBTAsmA1ixBvAUNEdAG5ggBc0AdgK4C2ARjtALzQCMADF9AFTQMAF3gA6ZNQAmAe3oAKAJQBufIWIAHRNKEpgOydGDTqEIYlp7piRQWJ3DxiNJApRIaQHM5AIgDC4KGgAQWgASxMhMGohULB9AEJvZTUiAF98dPwAeizoADMwS0QAT3xQSBgAdVDJDxQhCFsNRFCyHWhTONDgaAB9dSRUDGxEKgRkCHQsHBUU6E1WuJQOyJie8aHpxABlcI8XIWM2QwCYFAAPHSkYDcnhlib7Fa6e4EQUJZs5p6Jq2vqIKJ+oM7ltjtQUAB3OAgqYjRQqH72LICILUYrQFzUDwiDFgSSSUKHKIgBzUPKhDy0ZAxI6HaDMaAyCHQMB5HSIMLUImxEChABeXSOwCiDOWzOW8Bwyz4WW+xHSdkVxDmnTW0DqQhhEzhOC+SNCeTkf01gOBOvunNY7DoIBACnlTxNANEt11Oz2B2MojeHx0CMd0HeQmp1GgzoaQIGFq2iIVGVURhMzlc7i8EcBbstojI9tmSdM0Fw2s2Iyo4U61GAy1Sxwz+ccKbcnjkFciVdcueUQA)

**Comment by meganindya** [comment]
Your solution works for your use case: when there is a manager object. This is a different scenario.

The issue's requirement is based on [this](https://github.com/sugarlabs/musicblocks-2/discussions/11). Observe that there are different types of associations between classes. More often than not, there are independent classes, rather than classes managed by other classes. They might me instantiated at different times from multiple places, hence the necessity for singletons.

Not sure a top-level object dictionary will be a good idea. MB 1.0 has this problem. We do not want God objects. If you'll observe, `js/activity.js` in MB 1.0 instantiates everything irrespective of whether we need them or not. And therefore, we couldn't modularize the application.
