### ISSUE TITLE
Collect asset sizes from build

### ISSUE THREAD

**Issue by meganindya** [sugarlabs/musicblocks-2#288]
The bundle sizes of some modules are collected during build in `dist/stats.json`. However, the sizes of assets are not reported.

The goal here is to augment that stats file with file sizes of the assets bundled from `assets/`.

See `src/tools/scripts/stats/index.ts` and `src/tools/scripts/build.ts`.

**Comment by Aakarshan-369** [comment]
Hi! I'm trying to install the dependencies using `npm ci` in gitpod but getting an authentication error : 
`npm ERR! 401 Unauthorized - GET https://npm.pkg.github.com/download/@sugarlabs/musicblocks-v4-lib/0.2.0/f169ab57da6e2c473962d1e2575b3832bb18c35f - authentication token not provided`
I'm new and was just looking around good first issues. Any input on this error is appreciated :) 
thanks!

**Comment by SarthakKl** [comment]
Hi @meganindya, I want to contribute to this project and I am new to open source. I have some practical experience in ReactJs and javascript. Can you please help me in solving this issue?

**Comment by meganindya** [comment]
I actually have a WIP. See branch [288-bundle-sizes-splash-progress](https://github.com/sugarlabs/musicblocks-v4/tree/288-bundle-sizes-splash-progress). Make your PR onto this branch.

In [src/app/index.ts#L103](https://github.com/sugarlabs/musicblocks-v4/blob/c6315dc5cee659bb7adaa011d004e00290557943/src/app/index.ts#L103) you need to use the `stats` data to update the progress.

Currently, the progress bar updates on the basis of `(items loaded count / total items to be loaded count)`. It needs to be on the basis of `(items loaded size / total items to be loaded size)`.

In dev mode, you need to build the project once to get the stats data (or it'll be undefined). Let me know if you have any questions.

**Comment by SarthakKl** [comment]
I tried installing the dependencies, but I got this unauthorized error. How can I resolve this?
![Screenshot (25)](https://user-images.githubusercontent.com/86782712/213930578-38c3338e-e431-4674-94e2-81dad2e8fcfe.png)

**Comment by meganindya** [comment]
https://github.com/sugarlabs/musicblocks-v4/blob/develop/docs/DEV.md#commands

**Comment by niloysikdar** [comment]
Hi @meganindya, I would like to work on this issue.

**Comment by niloysikdar** [comment]
Hi @meganindya, I found one bug related to this context.

Note: I'm using `Windows 10 OS`, not sure what's the case for this in `linux` or `macOS`

I ran `npm run build` and checked the generated `dist/stats.json` file data.
However, I found the `i18n` and `assets` data to be missing.

```json
{
  "i18n": {},
  "assets": {},
  "modules": { "menu": 1394, "singer": 226021, "editor": 35200, "painter": 219016 }
}
```

I double checked to make sure the data is actually present in the `i18n` and `assets` dirMaps, and found that there is some data for both keys.

I then deep dived into the functions and how the data is getting generated and found the bug.

Firstly, when we are saving the `VisualizerData` into the `dist/stats.json` file, we are getting the Absolute Paths of the files inside the `id` of `nodeMetas`.

That's why `id.startsWith(prefix)` is failing in [scripts/stats/index.ts#L55](https://github.com/sugarlabs/musicblocks-v4/blob/288-bundle-sizes-splash-progress/tools/scripts/stats/index.ts#L55) and it is basically returning an empty array.

One simple solution is to use `id.includes(prefix)` instead of `id.startsWith(prefix)`, but then again we need to fix the logic to structure the key in [scripts/stats/index.ts#L57](https://github.com/sugarlabs/musicblocks-v4/blob/288-bundle-sizes-splash-progress/tools/scripts/stats/index.ts#L57) to actually remove the root path from the `Absolute Path` and then replace the `prefix` with an empty string to only get the fileName as the key.

Please let me know what we can do and which approach should we follow to fix this problem.

Again, it's happening on my Windows machine, not sure about Linux or macOS. Can you please confirm once if you're using Linux or macOS?

**Comment by meganindya** [comment]
Can you please create a new issue with `label: bug` and add the generated `stats.json` (the one generated by `visualizer` plugin before it is overwritten) into the description?

**Comment by meganindya** [comment]
Thanks for pointing out. Need to be careful when dealing with raw path strings because win32 path format is slightly different from that of linux or darwin.

**Comment by niloysikdar** [comment]
Sure @meganindya , I'm opening the issue.
Also, should we put a platform check using `process.platform` and detect if the platform is `win32` ? In that case we can do the prefix check or else generating the ids differently.

**Comment by meganindya** [comment]
The scripts under `/tools` are executed by `node` and not the browser so I'm sure that'll work. But I want to avoid hacks. We must implement something consistent.

**Comment by niloysikdar** [comment]
Yep, the scrips under `tools` are executed using node environment only. So, ideally we'll be able to use `process.platform` and it shouldn't throw any error or issue.

I also agree on the point to avoid hacks 😅 
But ig for now, this can be a temporary solution that came into my mind, we can discuss further to implement consistent solution.
Do you have any ideas in your mind to fix this ?

**Comment by meganindya** [comment]
Perhaps the `path` module could be of help. Nevertheless, please go ahead and make a PR. But, I'll want to keep the issue around.

**Comment by niloysikdar** [comment]
Sure will raise the PR with the fix. Also, submitted the issue here: #302 
Seems like I don't have the permission to add `label: bug` to the issue. Probably you can do that.
